### ISSUE TITLE
TypeError: unicode not allowed, use setsockopt_string with python 3.2 on Debian Wheezy

### ISSUE THREAD

**Issue by binary-data** [InviteBox/django-live-profiler#22]
Hi
I am launching server with `aggregated --host 127.0.0.1 --port 5556` and it throws me an exception:
Traceback (most recent call last):
  File "/home/webapp/www/env/bin/aggregated", line 9, in <module>
    load_entry_point('django-live-profiler==0.0.9', 'console_scripts', 'aggregated')()
  File "/home/webapp/www/env/lib/python3.2/site-packages/aggregate/server.py", line 73, in main
    socket.setsockopt(zmq.SUBSCRIBE,'')
  File "socket.pyx", line 310, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3184)
TypeError: unicode not allowed, use setsockopt_string

I use python 3.2 on Debian Wheezy and virtualenv.

**Comment by Matt3o12** [comment]
Doesn't work on Mac OS X Yosemite using python 3.3 either.  
Have you found a fix for that, yet?

**Comment by mchccc** [comment]
Just add a 'b' on line 73 in server.py, like so:

```
socket.setsockopt(zmq.SUBSCRIBE, b'')
```

**Comment by binary-data** [comment]
Closing because it seems a little outdated :)

**Comment by techdragon** [comment]
@binary-data I just got this issue with the current pypi package.

**Comment by binary-data** [comment]
@techdragon I don't think that this will be fixed, last update of this repo was three years ago :)

**Comment by pra-dan** [comment]
Just an addition/alternative to the answer above, 

```python3
topicfilter = 10005
socket.setsockopt(zmq.SUBSCRIBE, bytes(topicfilter))
```

**Comment by aminPial** [comment]
Just an addition/alternative to the answer above, (2)

```python3
topicfilter = 10005
socket.setsockopt(zmq.SUBSCRIBE, str.encode(topicfilter)) # basically we need byte repr. that's it
```
